server:
   port:8080
mybatis:
   type-aliases-package:com.neo.entity

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=utf-8
      username: root
      password: i
      
      
