server:
   port:8080

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=utf-8
      username: root
      password: i
   jpa:
      show-sql: true
      properties: 
         hibernate: 
            format_sql: true
      hibernate: 
         naming: 
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   view: 
      prefix: /WEB-INF/views/
      suffix: .jsp
      
      
