server:
   port: 8080
activiti:
    check-process-definitions: false
    # database-schema: activiti_spring_boot
    database-schema-update: false
    history-level: full
    db-history-used: true
spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://bjrdc37:3306/activiti_driver?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: bjrdc
      password: xjgz@123
      hikari:
        maxLifetime: 1765000 
        maximumPoolSize: 60 
        connectionTestQuery: SELECT 1 
   jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
   mvc: 
        view: 
             prefix: /WEB-INF/views/business/
             suffix: .jsp

   thymeleaf: 
      prefix: /WEB-INF/views/business/
      suffix: .jsp
      cache: false
      enabled: false
   servlet: 
      multipart: 
          maxFileSize: 30MB
          maxRequestSize: 30MB
          enabled: true

logging:
   level:
      cn.taocheng.activiti.driver : info
   pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

 

      
      
