server:
   port:8080
mybatis:
   type-aliases-package: cn.xportal.sb.ibatis.entity
   table:
      auto: update
spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://bjrdc37:3306/spring_boot?useUnicode=true&characterEncoding=utf-8
      username: bjrdc
      password: xjgz@123
      
      
