server:
  port: 8081
spring:
  security:
    basic:
      enabled: true
    user:
      name: root
      password: i
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: http://git.tsnail.cn:19090/spring-cloud-config.git
          searchPaths: '{application}'
          username: i
          password: i
eureka:
  client:
    service-url:
      defaultZone: http://root:i@localhost:8080/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: config